"""State file load/write round trip, per docs/design.md §5."""

from __future__ import annotations

from pathlib import Path

import pytest

from filepawl.errors import StateError
from filepawl.state import Entry, State, load_state, write_state

EXAMPLE_BYTES = (
    b"# Generated by filepawl. Do not edit; run `filepawl accept`.\n"
    b"version = 1\n"
    b"\n"
    b"[allowance]\n"
    b'"hqptuner/conf/matrixconf.py" = { lines = 496 }\n'
    b'"triviajudge/core.py" = '
    b'{ lines = 444, reason = "Line record plus its readers" }\n'
)


def test_load_state_absent_file_gives_empty_state(tmp_path: Path) -> None:
    state = load_state(tmp_path)
    assert state == State()
    assert state.version == 1
    assert state.allowance == {}


def test_write_state_produces_exact_design_doc_example(tmp_path: Path) -> None:
    state = State(
        allowance={
            "hqptuner/conf/matrixconf.py": Entry(lines=496),
            "triviajudge/core.py": Entry(
                lines=444, reason="Line record plus its readers"
            ),
        }
    )
    write_state(tmp_path, state)
    raw = (tmp_path / ".filepawl.toml").read_bytes()
    assert raw == EXAMPLE_BYTES


def test_write_state_sorts_entries_by_path(tmp_path: Path) -> None:
    state = State(
        allowance={
            "z/last.py": Entry(lines=10),
            "a/first.py": Entry(lines=20),
            "m/middle.py": Entry(lines=30),
        }
    )
    write_state(tmp_path, state)
    text = (tmp_path / ".filepawl.toml").read_text(encoding="utf-8")
    paths = ("a/first.py", "m/middle.py", "z/last.py")
    positions = [text.index(f'"{p}"') for p in paths]
    assert positions == sorted(positions)


def test_write_state_omits_reason_when_unset(tmp_path: Path) -> None:
    state = State(allowance={"a.py": Entry(lines=10)})
    write_state(tmp_path, state)
    text = (tmp_path / ".filepawl.toml").read_text(encoding="utf-8")
    assert "reason" not in text


def test_round_trip_preserves_reason(tmp_path: Path) -> None:
    state = State(
        allowance={
            "a.py": Entry(lines=10, reason="grew for a good cause"),
            "b.py": Entry(lines=20),
        }
    )
    write_state(tmp_path, state)
    loaded = load_state(tmp_path)
    assert loaded == state


def test_write_state_rewrites_wholesale(tmp_path: Path) -> None:
    write_state(tmp_path, State(allowance={"old.py": Entry(lines=1)}))
    write_state(tmp_path, State(allowance={"new.py": Entry(lines=2)}))
    text = (tmp_path / ".filepawl.toml").read_text(encoding="utf-8")
    assert "old.py" not in text
    assert "new.py" in text


def test_load_state_raises_on_unparseable_toml(tmp_path: Path) -> None:
    (tmp_path / ".filepawl.toml").write_text("not [ valid toml", encoding="utf-8")
    with pytest.raises(StateError):
        load_state(tmp_path)


def test_load_state_raises_on_missing_version(tmp_path: Path) -> None:
    (tmp_path / ".filepawl.toml").write_text(
        '[allowance]\n"a.py" = { lines = 1 }\n', encoding="utf-8"
    )
    with pytest.raises(StateError):
        load_state(tmp_path)


def test_load_state_raises_on_unsupported_version(tmp_path: Path) -> None:
    (tmp_path / ".filepawl.toml").write_text("version = 2\n", encoding="utf-8")
    with pytest.raises(StateError):
        load_state(tmp_path)


def test_load_state_raises_on_unknown_top_level_key(tmp_path: Path) -> None:
    (tmp_path / ".filepawl.toml").write_text(
        "version = 1\nbogus = true\n", encoding="utf-8"
    )
    with pytest.raises(StateError):
        load_state(tmp_path)


def test_load_state_raises_on_non_int_lines(tmp_path: Path) -> None:
    (tmp_path / ".filepawl.toml").write_text(
        'version = 1\n\n[allowance]\n"a.py" = { lines = "many" }\n',
        encoding="utf-8",
    )
    with pytest.raises(StateError):
        load_state(tmp_path)
