"""State file: `.filepawl.toml`, per docs/design.md §5."""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path

import tomli_w

from filepawl.errors import StateError

STATE_FILE = ".filepawl.toml"
HEADER = "# Generated by filepawl. Do not edit; run `filepawl accept`.\n"

_SUPPORTED_VERSION = 1
_TOP_LEVEL_KEYS = {"version", "allowance"}
_ENTRY_KEYS = {"lines", "reason"}


@dataclass(frozen=True)
class Entry:
    lines: int
    reason: str | None = None


@dataclass(frozen=True)
class State:
    version: int = 1
    allowance: dict[str, Entry] = field(default_factory=dict)


def load_state(root: Path) -> State:
    """Load `.filepawl.toml` from `root`, or an empty State if absent."""
    path = root / STATE_FILE
    if not path.exists():
        return State()

    try:
        raw = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        raise StateError(f"{path}: unparseable TOML: {exc}") from exc

    unknown = set(raw) - _TOP_LEVEL_KEYS
    if unknown:
        raise StateError(f"{path}: unknown top-level key(s): {sorted(unknown)}")

    version = raw.get("version")
    if version is None:
        raise StateError(f"{path}: missing `version`")
    if version != _SUPPORTED_VERSION:
        raise StateError(f"{path}: unsupported version {version!r}")

    allowance: dict[str, Entry] = {}
    for name, entry in raw.get("allowance", {}).items():
        unknown_entry_keys = set(entry) - _ENTRY_KEYS
        if unknown_entry_keys:
            raise StateError(
                f"{path}: allowance[{name!r}]: unknown key(s): "
                f"{sorted(unknown_entry_keys)}"
            )
        lines = entry.get("lines")
        if not isinstance(lines, int) or isinstance(lines, bool):
            raise StateError(f"{path}: allowance[{name!r}]: `lines` is not an int")
        allowance[name] = Entry(lines=lines, reason=entry.get("reason"))

    return State(version=version, allowance=allowance)


def _format_key(name: str) -> str:
    key, _, _ = tomli_w.dumps({name: 0}).partition(" = ")
    return key


def _format_entry(entry: Entry) -> str:
    fields = [f"lines = {entry.lines}"]
    if entry.reason is not None:
        fields.append(tomli_w.dumps({"reason": entry.reason}).strip())
    return "{ " + ", ".join(fields) + " }"


def write_state(root: Path, state: State) -> None:
    """Rewrite `.filepawl.toml` wholesale from `state`."""
    path = root / STATE_FILE
    chunks = [HEADER, tomli_w.dumps({"version": state.version})]
    if state.allowance:
        chunks.append("\n[allowance]\n")
        for name in sorted(state.allowance):
            entry = state.allowance[name]
            chunks.append(f"{_format_key(name)} = {_format_entry(entry)}\n")
    path.write_text("".join(chunks), encoding="utf-8")
